In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.mixture import GaussianMixture
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("Data_processed.csv")
data.head()

Formula  Excitation  Emission    4T1    4T2  \
0     K2Ti0.992F6Mn0.008         450       630  405.0  450.0   
1     K2Ti0.999F6Mn0.001         450       631  405.0  450.0   
2     K2Ti0.843F6Mn0.157         450       636  405.0  450.0   
3     K2Ti0.843F6Mn0.157         450       631  405.0  450.0   
4  Mg2Ti0.9999O4Mn0.0001         475       655  325.0  475.0   

                                          Ref    H   Li  Be    B  ...  Cs  Ba  \
0  https://doi.org/10.1038/s41377-018-0013-1   0.0  0.0   0  0.0  ...   0   0   
1   https://doi.org/10.1038/s41377-018-0013-1  0.0  0.0   0  0.0  ...   0   0   
2   https://doi.org/10.1038/s41377-018-0013-1  0.0  0.0   0  0.0  ...   0   0   
3   https://doi.org/10.1038/s41377-018-0013-1  0.0  0.0   0  0.0  ...   0   0   
4          https://doi.org/10.1039/C3TC30553H  0.0  0.0   0  0.0  ...   0   0   

    La   Eu   Gd   Lu   Ta    W   Pb   Bi  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 50 columns]

In [3]:
data.columns

Index(['Formula', 'Excitation', 'Emission', '4T1', '4T2', 'Ref', 'H', 'Li',
       'Be', 'B', 'C', 'N', 'O', 'F', 'Na', 'Mg', 'Al', 'Si', 'P', 'Cl', 'K',
       'Ca', 'Sc', 'Ti', 'V', 'Mn', 'Co', 'Zn', 'Ga', 'Ge', 'Rb', 'Sr', 'Y',
       'Zr', 'Nb', 'Mo', 'In', 'Sn', 'Sb', 'Te', 'Cs', 'Ba', 'La', 'Eu', 'Gd',
       'Lu', 'Ta', 'W', 'Pb', 'Bi'],
      dtype='object')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1734 entries, 0 to 1733
Data columns (total 50 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Formula     1734 non-null   object 
 1   Excitation  1734 non-null   int64  
 2   Emission    1734 non-null   int64  
 3   4T1         1701 non-null   float64
 4   4T2         1701 non-null   float64
 5   Ref         1734 non-null   object 
 6   H           1734 non-null   float64
 7   Li          1734 non-null   float64
 8   Be          1734 non-null   int64  
 9   B           1734 non-null   float64
 10  C           1734 non-null   int64  
 11  N           1734 non-null   int64  
 12  O           1734 non-null   float64
 13  F           1734 non-null   float64
 14  Na          1734 non-null   float64
 15  Mg          1734 non-null   float64
 16  Al          1734 non-null   float64
 17  Si          1734 non-null   float64
 18  P           1734 non-null   float64
 19  Cl          1734 non-null  

In [5]:
# features = ['Emission']
features = ['Excitation', 'Emission']
a = data[features]
a = a.values
np.shape(a), a

((1734, 2),
 array([[450, 630],
        [450, 631],
        [450, 636],
        ...,
        [460, 636],
        [460, 632],
        [467, 634]], dtype=int64))

In [6]:
results  = ['H', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F',
       'Na', 'Mg', 'Al', 'Si', 'P', 'Cl', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Mn',
       'Co', 'Zn', 'Ga', 'Ge', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'In', 'Sn',
       'Sb', 'Te', 'Cs', 'Ba', 'La', 'Eu', 'Gd', 'Lu', 'Ta', 'W', 'Pb', 'Bi']
b = data[results]
b = b.values
np.shape(b), b

((1734, 44),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

### Spliting dataset

In [7]:
from sklearn.model_selection import train_test_split
a_train, a_valid, b_train, b_valid = train_test_split(a, b, test_size=0.2, random_state = 24)

In [8]:
a_train.shape, b_valid.shape

((1387, 2), (347, 44))

### 1.ExtraTreesRegressor

In [9]:
from sklearn.ensemble import ExtraTreesRegressor
et_model = ExtraTreesRegressor(random_state =1)
et_model.fit(a_train, b_train)
et_preds = et_model.predict(a_valid)
et_preds.shape

(347, 44)

In [10]:
from sklearn.metrics import mean_squared_error, r2_score
print("RMSR ExtraTreesRegressor: %f" %np.sqrt(mean_squared_error(b_valid, et_preds)))
print("R2 ExtraTreesRegressor: %f %%" %(100*r2_score(b_valid, et_preds)))

RMSR ExtraTreesRegressor: 0.549245
R2 ExtraTreesRegressor: 78.268138 %


In [11]:
et_model.predict([[350, 680]])

array([[0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        6.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 2.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 4.600e-03, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 9.954e-01, 0.000e+00,
        0.000e+00, 0.000e+00]])

In [12]:
from joblib import dump

dump(et_model, "extratrees_inverse_model.joblib")


['extratrees_inverse_model.joblib']

In [17]:
import pandas as pd
import numpy as np

if len(et_preds.shape) == 2 and et_preds.shape[1] == len(results):
    df = pd.DataFrame(et_preds, columns=results)
else:
    # Nếu chỉ có 1 giá trị dự đoán mỗi mẫu
    df = pd.DataFrame({'Predicted_Value': et_preds})

# Thêm các cột đầu vào Excitation và Emission
df[features] = a_valid

# Đưa Excitation và Emission lên đầu
cols = features + [c for c in df.columns if c not in features]
df = df[cols]

# Lưu ra file CSV
df.to_csv("ET_predictions_inverse_design.csv", index=False)

print("✅ Successfull save Et_predictions_inverse_design.csv")

df.head()

✅ Successfull save Et_predictions_inverse_design.csv


Excitation  Emission    H   Li   Be    B    C    N    O    F  ...   Cs  \
0         365       695  0.0  0.0  0.0  0.0  0.0  0.0  6.0  0.0  ...  0.0   
1         450       692  0.0  0.0  0.0  0.0  0.0  0.0  6.0  0.0  ...  0.0   
2         348       696  0.0  0.0  0.0  0.0  0.0  0.0  6.0  0.0  ...  0.0   
3         366       681  0.0  0.0  0.0  0.0  0.0  0.0  6.0  0.0  ...  0.0   
4         470       668  0.0  3.0  0.0  0.0  0.0  0.0  6.0  0.0  ...  0.0   

    Ba   La   Eu   Gd   Lu        Ta       W   Pb   Bi  
0  0.0  0.5  0.0  0.0  0.0  0.000000  0.9825  0.0  0.0  
1  2.0  0.0  0.0  0.0  0.0  0.992500  0.0000  0.0  0.0  
2  0.0  1.0  0.0  0.0  0.0  0.000000  0.9965  0.0  0.0  
3  2.0  1.0  0.0  0.0  0.0  0.992543  0.0000  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.000000  0.0000  0.0  0.0  

[5 rows x 46 columns]

In [19]:
import pandas as pd

f_preds = []
f_trues = []

for i in range(len(b_valid)):
    f_pred = ''
    f_true = ''
    
    for j in range(len(results)):
        if et_preds[i, j] != 0:
            f_pred += f"{results[j]}{et_preds[i, j]:.2f}"  # Làm tròn 2 chữ số sau dấu phẩy
    f_preds.append(f_pred)

    for j in range(len(results)):
        if b_valid[i, j] != 0:
            f_true += f"{results[j]}{b_valid[i, j]:.2f}"  # Làm tròn 2 chữ số sau dấu phẩy
    f_trues.append(f_true)

# Tạo DataFrame từ a_valid (dữ liệu đặc trưng) và thêm cột công thức
data_preds = pd.DataFrame(a_valid, columns=features)
data_preds['Actual formula'] = f_trues
data_preds['Predicted formula'] = f_preds

# Ghi ra file CSV với 2 chữ số sau dấu phẩy cho các giá trị số
data_preds.to_csv('Inverse_design_Mn4+.csv', index=False, float_format="%.2f")

data_preds.head()

Excitation  Emission                           Actual formula  \
0         365       695  O6.00Mg1.00K0.50Mn0.00Sr1.00La0.50W1.00   
1         450       692             O6.00Mn0.00Y1.00Ba2.00Ta1.00   
2         348       696        O6.00Mg1.00K1.00Mn0.01La1.00W0.98   
3         366       681            O6.00Mn0.02Ba2.00La1.00Ta0.99   
4         470       668            Li3.00O6.00Mg2.00Mn0.00Nb1.00   

                         Predicted formula  
0  O6.00Mg1.00K0.50Mn0.02Sr1.00La0.50W0.98  
1             O6.00Mn0.01Y1.00Ba2.00Ta0.99  
2        O6.00Mg1.00K1.00Mn0.00La1.00W1.00  
3            O6.00Mn0.01Ba2.00La1.00Ta0.99  
4            Li3.00O6.00Mg2.00Mn0.00Nb1.00

### If you want to use the trained model, please refer to the code section below.

In [20]:
from joblib import load

et_model = load("extratrees_model.joblib")

###### 